name: Pull Request

on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint & Test
        uses: ./.github/actions/build
      - name: Build
        run: yarn run build
        shell: bash
      - name: Test
        run: yarn test
        shell: bash
